services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx-assist
    restart: unless-stopped
    ports:
      - "1082:80"
      # - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./static:/static
      - ./ssl:/etc/ssl
    networks:
      - assistant_api_network

  db:
    image: postgres:15
    restart: unless-stopped
    container_name: db-assist
    environment:
      POSTGRES_PASSWORD: "2yZnWGfq8G"
      PGDATA: "/var/lib/postgresql/pgdata"
    networks:
      - assistant_api_network
    ports:
      - "5435:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/pgdata

  user-grpc:
    image: voklem/user_grpc
    restart: unless-stopped
    container_name: user-grpc-assist
    networks:
      - assistant_api_network
    depends_on:
      - db
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data

  user-http:
    image: voklem/user_http
    restart: unless-stopped
    container_name: user-http-assist
    networks:
      - assistant_api_network
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data
      - ./ssl:/ssl

  assistant-http:
    image: voklem/assistant_http
    restart: unless-stopped
    container_name: assistant-http-assist
    networks:
      - assistant_api_network
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data

  assistant-grpc:
    image: voklem/assistant_grpc
    restart: unless-stopped
    container_name: assistant-grpc-assist
    depends_on:
      - db
    networks:
      - assistant_api_network
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data

  ted-api:
    image: voklem/ted_api
    restart: unless-stopped
    container_name: ted-api
    networks:
      - assistant_api_network
    ports:
      - "50055:50055"
    volumes:
      - ./logs/services:/logs/services
      - ./filestorage_data:/ted_api/filestorage_data

  integration-http:
    image: voklem/integration_http
    restart: unless-stopped
    container_name: integration-http-assist
    networks:
      - assistant_api_network
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data

  integration-grpc:
    image: voklem/integration_grpc
    restart: unless-stopped
    container_name: integration-grpc-assist
    networks:
      - assistant_api_network
    depends_on:
      - db
    volumes:
      - ./logs/services:/logs/services
      - ./static:/static
      - ./filestorage_data:/filestorage_data

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./model_files:/model_files
    container_name: ollama-assist
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
    networks:
      - assistant_api_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  assistant_api_network:
    driver: bridge
